### ISSUE TITLE
Safe Travel Infos - Lacobus not displaying correct details

### ISSUE THREAD

**Issue by ajlhowie** [rhoffsch42/DualUniverse-public#1]
When traveling between Lacobus and Ion the trajectory was too steep in the magnitude of many 10's of SU. This was when I was just starting my journey. My understanding is that the location of Lacobus may have changed in a recent update. I know ArchHud had to make an update to their LUA.

**Comment by rhoffsch42** [comment]
Thank you for the feedback, this should be fixed now on version 1.8.
The official atlas is now used, don't hesitate to tell me if something is wrong, I let the issue open for now.
